# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WebShop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WebShop
  pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :tag => '4.2.0'

end
